"""create webhook_events table

Revision ID: ce40322695c2
Revises: ae210956d3ac
Create Date: 2025-06-12 15:21:39.977060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce40322695c2'
down_revision: Union[str, None] = 'ae210956d3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('webhook_id'),
    sa.UniqueConstraint('webhook_id')
    )
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.drop_constraint(op.f('payments_razorpay_payment_id_key'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.create_unique_constraint(op.f('payments_razorpay_payment_id_key'), 'payments', ['razorpay_payment_id'])
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
